version: '3'
services:
  postgresql:
    image: postgres:latest
    container_name: crypto
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DATABASE=chat_api
    command: postgres
    restart: always
